export const SAVE_INFO_REQUEST = "SAVE_INFO_REQUEST";
export const SAVE_INFO_SUCCESS = "SAVE_INFO_SUCCESS";
export const SAVE_INFO_FAILURE = "SAVE_INFO_FAILURE";

export const GET_INFO_REQUEST = "GET_INFO_REQUEST";
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_FAILURE = "GET_INFO_FAILURE";